import { useState } from "react";
import { Link } from "react-router-dom";
import { motion, AnimatePresence } from "framer-motion";
import SectionHeader from "@/components/ui/SectionHeader";
import { CTASection } from "@/pages/Home/sections/CTASection";
import { useContactModal } from "@/components/layout/ContactModal";
import {
  LockIcon,
  ShieldIcon,
  KeyIcon,
  BellIcon,
  AlertTriangleIcon,
  CpuIcon,
  ActivityIcon,
  EyeIcon,
  GearIcon,
} from "@/components/icons";

/* ───────── MFA VENDORS LINEUP (HONEYCOMB) ───────── */

const vendorLineup: { slug: string; name: string; logo: string }[] = [
  { slug: "okta-mfa", name: "Okta", logo: "/logos/Okta.png" },
  { slug: "microsoft-entra-mfa", name: "Microsoft Entra MFA", logo: "/logos/microsoft.svg" },
  { slug: "cisco-duo", name: "Cisco Duo", logo: "/logos/Cisco.svg" },
  { slug: "rsa-securid", name: "RSA SecurID", logo: "/logos/RSA_SecurID.png" },
  { slug: "yubico", name: "Yubico (YubiKey)", logo: "/logos/yubico.svg" },
  { slug: "google-workspace-mfa", name: "Google Workspace MFA", logo: "/logos/Google-Cloud.webp" },
];

/* ───────── DATA ───────── */

const stats: { value: string; label: string }[] = [
  {
    value: "99.9%",
    label: "Of automated account attacks blocked by MFA (Microsoft data)",
  },
  {
    value: "80%",
    label: "Of breaches that involve compromised credentials",
  },
  {
    value: "15 min",
    label: "Average time for attackers to exploit a freshly compromised account",
  },
];

type CapAccent = "cyan" | "amber" | "emerald" | "violet" | "rose" | "teal";

const methods: {
  title: string;
  desc: string;
  icon: typeof LockIcon;
  accent: CapAccent;
  tag: string;
}[] = [
  {
    title: "Push Notification (App-Based)",
    desc: "A login attempt appears on your phone via an authenticator app (Microsoft Authenticator, Okta Verify, Duo). You approve or deny it. Convenient, fast, and resistant to credential stuffing. Vulnerable to MFA fatigue attacks, repeated push spam hoping the user accidentally approves.",
    icon: BellIcon,
    accent: "cyan",
    tag: "Strong",
  },
  {
    title: "TOTP (Time-Based One-Time Password)",
    desc: "A 6-digit code generated by an app (Google Authenticator, Microsoft Authenticator) that changes every 30 seconds. No internet required. Works offline. More phishing-resistant than SMS but still vulnerable to real-time phishing if the user is tricked into entering the code on a fake site.",
    icon: CpuIcon,
    accent: "emerald",
    tag: "Strong",
  },
  {
    title: "SMS One-Time Password",
    desc: "A code sent via text message. Convenient and widely supported but the weakest form of MFA. Vulnerable to SIM swapping (an attacker porting your number to their SIM) and SS7 network attacks. NIST deprecated SMS OTP as a standalone MFA factor in 2016. Use only as a fallback, never as a primary factor.",
    icon: AlertTriangleIcon,
    accent: "rose",
    tag: "Weak",
  },
  {
    title: "Hardware Security Key (FIDO2)",
    desc: "A physical device (YubiKey, Google Titan) that plugs into USB or taps via NFC. The strongest MFA factor available. Completely phishing-resistant because the key uses a challenge-response protocol tied to the specific domain, it cannot be tricked by a fake login page because the domain mismatch causes it to reject the authentication.",
    icon: KeyIcon,
    accent: "amber",
    tag: "Phishing-Resistant",
  },
  {
    title: "Smart Card / Certificate",
    desc: "Common in government and high-security environments. A card with an embedded cryptographic chip (PIV, CAC). The strongest enterprise MFA for environments requiring compliance with government security standards. Requires infrastructure to issue and manage certificates.",
    icon: ShieldIcon,
    accent: "violet",
    tag: "Phishing-Resistant",
  },
  {
    title: "Biometric",
    desc: "Face ID, Touch ID, Windows Hello. Device-bound biometric verification that never sends biometric data to a server, the match happens locally on the device. Excellent UX, no tokens to carry. The foundation of modern passkey authentication. As strong as the device security backing it.",
    icon: LockIcon,
    accent: "teal",
    tag: "Phishing-Resistant",
  },
  {
    title: "Phishing-Resistant MFA (FIDO2 / Passkeys)",
    desc: "Beyond hardware keys, FIDO2 and WebAuthn now underpin passkeys that sync across devices. Authentication is cryptographically bound to the legitimate domain, so there is no shared secret to steal and no code to phish. This is the only class of factor that defeats real-time phishing and man-in-the-middle proxy attacks outright.",
    icon: ShieldIcon,
    accent: "cyan",
    tag: "Phishing-Resistant",
  },
  {
    title: "Adaptive / Risk-Based MFA",
    desc: "Step-up authentication is triggered only when risk is elevated, using device posture, location, network reputation, and behavioural signals to score each attempt. Impossible-travel detection catches a login from two continents minutes apart. Low-risk logins stay frictionless, which keeps users from working around the control.",
    icon: AlertTriangleIcon,
    accent: "amber",
    tag: "Strong",
  },
  {
    title: "Passwordless Authentication",
    desc: "Sign in with no password at all, using Windows Hello, passkeys, or platform biometrics as the primary factor. Removing the password removes the single largest attack surface in identity, there is nothing to phish, reuse, or leak in a breach. The user experience is faster than a password, which drives adoption rather than resistance.",
    icon: KeyIcon,
    accent: "emerald",
    tag: "Phishing-Resistant",
  },
  {
    title: "Legacy & Service Account MFA",
    desc: "Not every system can take a modern agent. Agentless enforcement, RADIUS, and proxy patterns bring MFA to command-line tools, RDP sessions, VPNs, and legacy applications that were never built for it. Service accounts and machine identities are secured without breaking the automation that depends on them.",
    icon: CpuIcon,
    accent: "violet",
    tag: "Strong",
  },
  {
    title: "Conditional Access & Policy",
    desc: "Policy decisions are made per application, user, device, and risk level rather than as a blanket rule. Device-trust and compliance checks gate sensitive access, legacy authentication protocols are blocked outright, and enforcement stays context-aware and continuous across the session. The result is security that tightens exactly where it matters.",
    icon: BellIcon,
    accent: "rose",
    tag: "Strong",
  },
];

/* ───────── WHAT MFA COVERS (BUILDING BLOCKS) ───────── */

const mfaBuildingBlocks: {
  icon: typeof LockIcon;
  title: string;
  points: string[];
}[] = [
  {
    icon: BellIcon,
    title: "Push & App-Based Authentication",
    points: [
      "One-tap approval via Authenticator, Okta Verify, Duo",
      "Number matching to defeat MFA fatigue attacks",
      "Login context: location, app and device shown",
      "TOTP soft tokens that work fully offline",
    ],
  },
  {
    icon: KeyIcon,
    title: "Phishing-Resistant Factors",
    points: [
      "FIDO2 / WebAuthn hardware keys (YubiKey, Titan)",
      "Device-bound passkeys that sync securely",
      "Smart cards and certificates (PIV, CAC)",
      "Domain-bound challenge-response, no shared secret",
    ],
  },
  {
    icon: LockIcon,
    title: "Biometric & Passwordless",
    points: [
      "Windows Hello, Face ID and Touch ID sign-in",
      "Passwordless as the primary factor, no password",
      "Local-only biometric match, never sent to a server",
      "Faster sign-in that drives adoption, not resistance",
    ],
  },
  {
    icon: ActivityIcon,
    title: "Adaptive & Risk-Based MFA",
    points: [
      "Step-up only when risk is elevated",
      "Impossible-travel and velocity detection",
      "Device posture, IP reputation and behaviour signals",
      "Frictionless low-risk logins, strong high-risk gates",
    ],
  },
  {
    icon: ShieldIcon,
    title: "Conditional Access & Policy",
    points: [
      "Per-app, per-user, per-device policy decisions",
      "Device-trust and compliance gating",
      "Legacy authentication protocols blocked outright",
      "Continuous, context-aware session enforcement",
    ],
  },
  {
    icon: CpuIcon,
    title: "Legacy & Service Account Coverage",
    points: [
      "Agentless enforcement via RADIUS and proxy",
      "MFA for RDP, VPN and command-line tools",
      "Machine and service identity protection",
      "Coverage without breaking existing automation",
    ],
  },
];

/* ───────── MFA ASSURANCE LADDER (FIVE STEPS) ───────── */

const mfaLadder: {
  tag: string;
  icon: typeof LockIcon;
  title: string;
  desc: string;
  details: string;
}[] = [
  {
    tag: "Step 1",
    icon: KeyIcon,
    title: "Single Factor",
    desc: "Password only.",
    details:
      "A password is a single shared secret that gets reused, phished, keylogged, and leaked in third-party breaches. Once compromised, the attacker has everything they need to impersonate the user completely. The baseline that every modern attack assumes you are still standing on.",
  },
  {
    tag: "Step 2",
    icon: BellIcon,
    title: "Basic MFA",
    desc: "Password plus a second factor.",
    details:
      "Add SMS, TOTP, or push as a second proof of identity. Even a basic second factor blocks the vast majority of automated credential-stuffing attacks. SMS is the weakest rung, vulnerable to SIM swapping, so treat it as a fallback rather than a primary factor.",
  },
  {
    tag: "Step 3",
    icon: ActivityIcon,
    title: "Adaptive MFA",
    desc: "Verify only when risk is elevated.",
    details:
      "Contextual signals (device posture, location, IP reputation, behaviour) decide when to step up and how strong the challenge must be. Low-risk logins stay frictionless, high-risk logins are challenged or blocked. This reduces MFA fatigue while tightening security exactly where it matters.",
  },
  {
    tag: "Step 4",
    icon: ShieldIcon,
    title: "Phishing-Resistant",
    desc: "Defeat real-time phishing.",
    details:
      "FIDO2 hardware keys, smart cards, and WebAuthn bind authentication cryptographically to the legitimate domain. There is no shared secret to steal and no code to phish, so real-time phishing and man-in-the-middle proxy attacks fail outright. The standard for privileged and executive accounts.",
  },
  {
    tag: "Step 5",
    icon: EyeIcon,
    title: "Passwordless & Continuous",
    desc: "Remove the password entirely.",
    details:
      "Passkeys, Windows Hello, and platform biometrics become the primary factor, removing the single largest attack surface in identity. Combined with continuous, conditional access that re-evaluates trust across the session, authentication becomes both stronger and faster than a password ever was.",
  },
];

/* ───────── PRINCIPLE QUOTE ───────── */

const quote = {
  text: "MFA blocks 99.9 percent of automated account-compromise attacks. No organisation that mandates MFA for every user has ever suffered the kind of mass credential-stuffing breach that regularly devastates organisations relying on passwords alone. It is not a perfect control. It is the single highest-ROI security investment available.",
  attribution: "The principle behind every MFA investment",
};

/* ───────── VENDOR COMPARISON MATRIX ───────── */

const matrixVendors: { name: string; recommended?: boolean; rank?: string }[] = [
  { name: "Okta", recommended: true },
  { name: "Microsoft Entra MFA", recommended: true },
  { name: "Cisco Duo", recommended: true },
  { name: "RSA SecurID" },
  { name: "Yubico (YubiKey)" },
  { name: "Google Workspace MFA" },
];

type StarCell = { stars: number; note: string };
type VerdictCell = { recommended?: boolean; rank?: string; text: string };
type MatrixRow =
  | { label: string; type: "text"; cells: string[] }
  | { label: string; type: "stars"; cells: StarCell[] }
  | { label: string; type: "verdict"; cells: VerdictCell[] };

const matrixRows: MatrixRow[] = [
  {
    label: "Founded / Heritage",
    type: "text",
    cells: [
      "MFA since 2009, cloud-native",
      "Azure MFA 2014, bundled in M365",
      "2010, acquired by Cisco 2018",
      "1986, MFA pioneer (SecurID)",
      "2007, hardware key inventor",
      "Workspace MFA since 2010",
    ],
  },
  {
    label: "Push MFA",
    type: "stars",
    cells: [
      { stars: 5, note: "Verify push, adaptive" },
      { stars: 5, note: "Authenticator + number matching" },
      { stars: 5, note: "Best push UX in market" },
      { stars: 4, note: "Authenticate app" },
      { stars: 3, note: "No push, key-based only" },
      { stars: 5, note: "Google prompt" },
    ],
  },
  {
    label: "TOTP",
    type: "stars",
    cells: [
      { stars: 5, note: "Verify TOTP" },
      { stars: 5, note: "Authenticator TOTP" },
      { stars: 5, note: "Native TOTP" },
      { stars: 5, note: "Soft tokens" },
      { stars: 5, note: "TOTP via OATH" },
      { stars: 5, note: "Google Authenticator" },
    ],
  },
  {
    label: "FIDO2 / Hardware Keys",
    type: "stars",
    cells: [
      { stars: 5, note: "FastPass + WebAuthn" },
      { stars: 5, note: "Windows Hello + Passkeys" },
      { stars: 5, note: "Native FIDO2" },
      { stars: 5, note: "Hybrid token support" },
      { stars: 5, note: "Best-in-class YubiKey" },
      { stars: 5, note: "Titan Security Key" },
    ],
  },
  {
    label: "Biometric",
    type: "stars",
    cells: [
      { stars: 5, note: "Okta Verify biometric" },
      { stars: 5, note: "Windows Hello" },
      { stars: 5, note: "Duo biometric" },
      { stars: 3, note: "Limited biometric" },
      { stars: 3, note: "Partial biometric" },
      { stars: 5, note: "Android/iOS biometric" },
    ],
  },
  {
    label: "SMS (Fallback)",
    type: "stars",
    cells: [
      { stars: 5, note: "SMS fallback" },
      { stars: 5, note: "SMS fallback" },
      { stars: 5, note: "SMS supported" },
      { stars: 5, note: "SMS supported" },
      { stars: 1, note: "No SMS" },
      { stars: 5, note: "SMS fallback" },
    ],
  },
  {
    label: "Adaptive / Risk-Based",
    type: "stars",
    cells: [
      { stars: 5, note: "Identity Threat Protection" },
      { stars: 5, note: "Conditional Access engine" },
      { stars: 5, note: "Risk-Based Authentication" },
      { stars: 5, note: "Adaptive engine" },
      { stars: 1, note: "Key only, no adaptive" },
      { stars: 3, note: "Workspace risk signals" },
    ],
  },
  {
    label: "Phishing Resistance",
    type: "stars",
    cells: [
      { stars: 5, note: "FastPass anti-phish" },
      { stars: 5, note: "Number matching + FIDO2" },
      { stars: 5, note: "Verified Push + FIDO2" },
      { stars: 4, note: "FIDO2 supported" },
      { stars: 5, note: "FIDO2 by design" },
      { stars: 5, note: "FIDO2 + Titan" },
    ],
  },
  {
    label: "Enterprise Scale",
    type: "stars",
    cells: [
      { stars: 5, note: "Workforce + customer" },
      { stars: 5, note: "M365 native scale" },
      { stars: 5, note: "Cisco enterprise scale" },
      { stars: 5, note: "Long enterprise track record" },
      { stars: 4, note: "Hardware logistics" },
      { stars: 4, note: "Workspace-centric scale" },
    ],
  },
  {
    label: "5-Year TCO (5,000 users)",
    type: "stars",
    cells: [
      { stars: 3, note: "Premium per-user" },
      { stars: 5, note: "Bundled in M365" },
      { stars: 4, note: "Per-user friendly" },
      { stars: 3, note: "Premium, hardware ops" },
      { stars: 4, note: "Hardware capex" },
      { stars: 5, note: "Bundled in Workspace" },
    ],
  },
  {
    label: "Passwordless",
    type: "stars",
    cells: [
      { stars: 4, note: "FastPass passwordless" },
      { stars: 5, note: "Windows Hello + passkeys" },
      { stars: 4, note: "Passwordless Duo" },
      { stars: 3, note: "Growing" },
      { stars: 5, note: "Passwordless via keys" },
      { stars: 4, note: "Passkeys" },
    ],
  },
  {
    label: "Legacy & Service Account Coverage",
    type: "stars",
    cells: [
      { stars: 3, note: "SaaS-first" },
      { stars: 3, note: "Cloud-first, limited legacy" },
      { stars: 3, note: "Some legacy" },
      { stars: 4, note: "Strong legacy/token base" },
      { stars: 3, note: "Key-based" },
      { stars: 2, note: "Cloud-first, limited legacy" },
    ],
  },
  {
    label: "Conditional Access Integration",
    type: "stars",
    cells: [
      { stars: 4, note: "Identity Threat Protection" },
      { stars: 5, note: "Best-in-class Conditional Access" },
      { stars: 4, note: "Device trust policies" },
      { stars: 3, note: "Policy engine" },
      { stars: 3, note: "Key-level only" },
      { stars: 3, note: "Context-Aware Access" },
    ],
  },
  {
    label: "Best Suited For",
    type: "text",
    cells: [
      "Multi-cloud workforce + customer IAM",
      "Microsoft 365 estates, Conditional Access driven",
      "MFA-first deployments, Cisco ecosystem",
      "Government, regulated, hardware-token estates",
      "High-risk accounts, executives, admins",
      "Google Workspace estates",
    ],
  },
  {
    label: "Strategic verdict",
    type: "verdict",
    cells: [
      { recommended: true, text: "Strongest workforce + customer MFA coverage with FastPass and Auth0. The pragmatic pick for multi-cloud." },
      { recommended: true, text: "Number matching, Conditional Access, included in M365. The default pick for Microsoft-aligned estates." },
      { recommended: true, text: "Best push UX in the market and device trust signals. The right pick for MFA-first deployments." },
      { text: "Longest enterprise MFA track record. The choice for government and hardware-token estates." },
      { text: "The strongest phishing-resistant factor available. Deploy for executives and admins as a layer." },
      { text: "Native Google Workspace integration with Titan keys. The natural pick for Workspace estates." },
    ],
  },
];

/* ───────── VENDOR DETAIL CARDS ───────── */

const vendors: {
  slug: string;
  name: string;
  best: string;
  strength: string;
  watch: string;
  logo: string;
}[] = [
  {
    slug: "okta-mfa",
    name: "Okta MFA",
    best: "Leader, Cloud-Native (Recommended)",
    strength:
      "Strongest cloud-native MFA, paired with Okta's broad app catalogue. FastPass delivers passwordless phishing-resistant authentication across Windows, Mac, iOS, and Android, with adaptive risk signals from Okta Identity Threat Protection across the 7,000-plus app catalogue.",
    watch:
      "Per-user licensing adds up at scale. Less native value for M365-centric organisations than Microsoft Entra.",
    logo: "/logos/Okta.png",
  },
  {
    slug: "microsoft-entra-mfa",
    name: "Microsoft Entra MFA",
    best: "Leader, Included in M365 (Recommended)",
    strength:
      "The most complete MFA platform for Microsoft environments. Conditional Access ties MFA policy to device compliance, location, and real-time risk from one engine. Number matching eliminates MFA fatigue and Windows Hello for Business delivers phishing-resistant sign-in.",
    watch:
      "Less value for non-Microsoft environments. Premium features require Entra ID P1 or P2 licensing.",
    logo: "/logos/microsoft.svg",
  },
  {
    slug: "cisco-duo",
    name: "Cisco Duo",
    best: "Leader, MFA-First (Recommended)",
    strength:
      "Built specifically for MFA from day one, with the cleanest push notification experience in the market. Device trust through Duo Device Health, and it works with any existing identity provider and application, improving any identity setup without replacing it.",
    watch:
      "Cisco ecosystem integration adds complexity for non-Cisco shops. Less advanced IGA and governance integration.",
    logo: "/logos/Cisco.svg",
  },
  {
    slug: "rsa-securid",
    name: "RSA SecurID",
    best: "Challenger, Enterprise Legacy",
    strength:
      "The MFA pioneer. RSA still commands significant share in large enterprises and government environments, particularly where hardware-token infrastructure already exists, with strong hybrid token plus software flexibility.",
    watch:
      "The 2011 breach still affects perception. More expensive and operationally heavier than modern cloud alternatives.",
    logo: "/logos/RSA_SecurID.png",
  },
  {
    slug: "yubico",
    name: "Yubico (YubiKey)",
    best: "Visionary, Hardware-First",
    strength:
      "The leading hardware security key. YubiKey provides phishing-resistant FIDO2 authentication for the highest-risk accounts, works with any FIDO2-compatible service, and needs no battery, app, or connectivity. A complement to an MFA platform, not a standalone replacement.",
    watch:
      "Physical token management overhead. Not a complete MFA management platform on its own.",
    logo: "/logos/yubico.svg",
  },
  {
    slug: "google-workspace-mfa",
    name: "Google Workspace MFA",
    best: "Challenger, Workspace Native",
    strength:
      "Native MFA for Google Workspace estates, bundled with Workspace licensing. Combined with Titan Security Keys, it delivers phishing-resistant coverage without an additional vendor contract, and Google prompt offers a smooth push experience.",
    watch:
      "Workspace-centric, limited beyond the Google estate. Risk-based capabilities less mature than Microsoft or Okta.",
    logo: "/logos/Google-Cloud.webp",
  },
];

/* ───────── GARTNER-STYLE SCORECARD ───────── */

const featureVendors = [
  "Okta",
  "Microsoft Entra MFA",
  "Cisco Duo",
  "RSA SecurID",
  "Yubico",
  "Google Workspace MFA",
];

type Tier = "best" | "excellent" | "veryStrong" | "strong" | "good" | "moderate";
type FeatureCell = { tier: Tier; note: string };

const featureRows: { label: string; cells: FeatureCell[] }[] = [
  {
    label: "Push MFA",
    cells: [
      { tier: "best", note: "Verify + adaptive" },
      { tier: "best", note: "Authenticator + number matching" },
      { tier: "best", note: "Cleanest push UX" },
      { tier: "veryStrong", note: "App + soft tokens" },
      { tier: "moderate", note: "Key-based, no push" },
      { tier: "veryStrong", note: "Google prompt push" },
    ],
  },
  {
    label: "TOTP",
    cells: [
      { tier: "best", note: "Verify TOTP" },
      { tier: "best", note: "Native Authenticator" },
      { tier: "best", note: "Native TOTP" },
      { tier: "excellent", note: "Soft tokens" },
      { tier: "excellent", note: "TOTP via OATH" },
      { tier: "best", note: "Google Authenticator" },
    ],
  },
  {
    label: "FIDO2 / Hardware Keys",
    cells: [
      { tier: "best", note: "FastPass + WebAuthn" },
      { tier: "best", note: "Windows Hello + Passkeys" },
      { tier: "best", note: "Native FIDO2 support" },
      { tier: "veryStrong", note: "Hybrid hardware support" },
      { tier: "best", note: "Category-defining YubiKey" },
      { tier: "best", note: "Titan Security Keys" },
    ],
  },
  {
    label: "Biometric",
    cells: [
      { tier: "best", note: "Okta Verify biometric" },
      { tier: "best", note: "Windows Hello" },
      { tier: "best", note: "Duo biometric" },
      { tier: "good", note: "Limited biometric" },
      { tier: "good", note: "Partial biometric" },
      { tier: "veryStrong", note: "Device biometric prompt" },
    ],
  },
  {
    label: "Adaptive / Risk-Based",
    cells: [
      { tier: "excellent", note: "Identity Threat Protection" },
      { tier: "best", note: "Conditional Access, 100+ signals" },
      { tier: "excellent", note: "Risk-Based Authentication" },
      { tier: "veryStrong", note: "Adaptive Access" },
      { tier: "moderate", note: "Hardware-only" },
      { tier: "good", note: "Basic risk signals, Workspace-centric" },
    ],
  },
  {
    label: "Phishing Resistance",
    cells: [
      { tier: "best", note: "FastPass anti-phishing" },
      { tier: "best", note: "Number matching plus FIDO2" },
      { tier: "best", note: "Verified Push plus FIDO2" },
      { tier: "veryStrong", note: "FIDO2 capable" },
      { tier: "best", note: "FIDO2 by design" },
      { tier: "best", note: "Titan keys plus FIDO2" },
    ],
  },
  {
    label: "Enterprise Scale",
    cells: [
      { tier: "best", note: "Workforce plus customer" },
      { tier: "best", note: "M365 native scale" },
      { tier: "best", note: "Cisco enterprise scale" },
      { tier: "excellent", note: "Long enterprise track record" },
      { tier: "good", note: "Hardware logistics scale" },
      { tier: "veryStrong", note: "Google global scale, Workspace estates" },
    ],
  },
  {
    label: "Passwordless",
    cells: [
      { tier: "veryStrong", note: "FastPass passwordless" },
      { tier: "best", note: "Windows Hello + passkeys" },
      { tier: "veryStrong", note: "Passwordless Duo" },
      { tier: "strong", note: "Growing" },
      { tier: "best", note: "Passwordless via keys" },
      { tier: "veryStrong", note: "Passkeys" },
    ],
  },
  {
    label: "Legacy & Service Account Coverage",
    cells: [
      { tier: "strong", note: "SaaS-first" },
      { tier: "strong", note: "Cloud-first, limited legacy" },
      { tier: "strong", note: "Some legacy" },
      { tier: "veryStrong", note: "Strong legacy/token base" },
      { tier: "strong", note: "Key-based" },
      { tier: "moderate", note: "Cloud-first, limited legacy" },
    ],
  },
  {
    label: "Conditional Access Integration",
    cells: [
      { tier: "veryStrong", note: "Identity Threat Protection" },
      { tier: "best", note: "Best-in-class Conditional Access" },
      { tier: "veryStrong", note: "Device trust policies" },
      { tier: "strong", note: "Policy engine" },
      { tier: "good", note: "Key-level only" },
      { tier: "strong", note: "Context-Aware Access" },
    ],
  },
  {
    label: "Deployment Breadth",
    cells: [
      { tier: "best", note: "7,000+ app catalog" },
      { tier: "best", note: "Native M365 + 1000s apps" },
      { tier: "best", note: "Fast, broad integrations" },
      { tier: "strong", note: "Enterprise-focused" },
      { tier: "strong", note: "Works via IdPs" },
      { tier: "veryStrong", note: "Workspace + SAML apps" },
    ],
  },
  {
    label: "Total Cost of Ownership",
    cells: [
      { tier: "moderate", note: "Premium per-user" },
      { tier: "best", note: "Bundled in M365" },
      { tier: "veryStrong", note: "Per-user friendly" },
      { tier: "moderate", note: "Premium, hardware ops" },
      { tier: "veryStrong", note: "Hardware capex amortised" },
      { tier: "best", note: "Bundled with Workspace licensing" },
    ],
  },
];

const tierStyles: Record<Tier, { bg: string; text: string; label: string }> = {
  best: { bg: "bg-emerald-600", text: "text-white", label: "Best in class" },
  excellent: { bg: "bg-emerald-500", text: "text-white", label: "Excellent" },
  veryStrong: { bg: "bg-emerald-200", text: "text-emerald-900", label: "Very strong" },
  strong: { bg: "bg-amber-200", text: "text-amber-900", label: "Strong" },
  good: { bg: "bg-amber-100", text: "text-amber-900", label: "Good" },
  moderate: { bg: "bg-amber-100", text: "text-amber-900", label: "Moderate" },
};

/* ───────── DECISION GUIDE ───────── */

const decisionGuide: { scenario: string; recommend: string }[] = [
  {
    scenario: "You run Microsoft 365 and Windows",
    recommend:
      "Microsoft Entra MFA with Conditional Access. Included in most M365 tiers, most deeply integrated with Windows Hello and Azure services, number matching eliminates push bombing.",
  },
  {
    scenario: "You have a mixed environment or want MFA as a standalone layer",
    recommend:
      "Cisco Duo. Works with any identity provider and any application. The simplest user experience, and vendor-neutral, it improves any existing identity setup without replacing it.",
  },
  {
    scenario: "You are in government or high-security enterprise with existing hardware tokens",
    recommend:
      "RSA SecurID Access. Longest track record, strongest hybrid token plus software support, still the reference implementation for government-grade MFA in many frameworks.",
  },
  {
    scenario: "You need phishing-resistant MFA for privileged or executive accounts",
    recommend:
      "Yubico YubiKey (FIDO2). Hardware keys are the only truly phishing-resistant factor. Deploy for admins, executives, and finance teams as a complement to your existing MFA platform.",
  },
  {
    scenario: "You are a Google Workspace organisation",
    recommend:
      "Google Workspace MFA with Google Authenticator and Titan Security Key. Deep integration within the Google ecosystem, Workspace MFA plus Titan keys provides phishing-resistant coverage without additional vendors.",
  },
];

/* ───────── FAQS ───────── */

const faqs = [
  {
    question: "What is Multi-Factor Authentication (MFA)?",
    answer:
      "MFA requires two or more independent proofs of identity before granting access: something you know (a password or PIN), something you have (a phone, hardware key, or smart card), and something you are (a fingerprint or face). Even if an attacker steals your password, they cannot log in without also possessing the second factor, which is why MFA is the single most impactful authentication control available.",
  },
  {
    question: "Why is MFA so effective against account takeover?",
    answer:
      "Microsoft reports that MFA blocks 99.9 percent of automated account compromise attacks. Those attacks are mostly credential-stuffing bots testing millions of leaked username and password pairs. Without the second factor the bots cannot proceed, so the attack fails at the exact point where it would otherwise succeed. A stolen password stops being sufficient on its own.",
  },
  {
    question: "What is phishing-resistant MFA?",
    answer:
      "Phishing-resistant MFA uses factors that are cryptographically bound to the legitimate domain, such as FIDO2 hardware keys, smart cards, and WebAuthn passkeys. There is no shared secret to steal and no code to type into a fake site, so real-time phishing and man-in-the-middle proxy attacks fail outright. It is the standard for privileged, finance, and executive accounts.",
  },
  {
    question: "Is SMS-based MFA safe to use?",
    answer:
      "SMS is the weakest form of MFA. It is vulnerable to SIM swapping, where an attacker ports your number to their SIM, and to SS7 network attacks. NIST deprecated SMS OTP as a standalone factor in 2016. SMS is still far better than no MFA, but use it only as a fallback, never as your primary factor.",
  },
  {
    question: "What is MFA fatigue and how do we defend against it?",
    answer:
      "MFA fatigue, or push bombing, is when an attacker who already has the password sends repeated push prompts until the user approves one out of frustration. This is how Uber was compromised in 2022. Defences include number matching (the user types a number shown on the login screen rather than just tapping approve), login context in the notification, and phishing-resistant FIDO2 keys for high-risk accounts.",
  },
  {
    question: "What is passwordless authentication and is it more secure?",
    answer:
      "Passwordless replaces the password entirely with a stronger primary factor: passkeys, Windows Hello, or platform biometrics. Removing the password removes the single largest attack surface in identity, there is nothing to phish, reuse, or leak in a breach. Because it is also faster than typing a password, adoption improves rather than meeting resistance. Every major vendor now pushes passwordless as the default for new deployments.",
  },
];

/* ───────── HERO ───────── */

function MfaHero() {
  const { open: openContact } = useContactModal();
  return (
    <section className="relative flex min-h-screen flex-col overflow-hidden bg-navy-deep">
      <div aria-hidden="true" className="absolute inset-0 bg-cover bg-center" style={{ backgroundImage: "url('/network-security.jpg')" }} />
      <div aria-hidden="true" className="absolute inset-0 bg-gradient-to-b from-navy-deep/85 via-navy-deep/70 to-navy-deep/90" />

      <div className="relative z-10 border-b border-white/5">
        <div className="shell flex w-full items-center justify-end gap-4 pt-24 pb-3 sm:pt-28">
          <nav aria-label="Breadcrumb">
            <ol className="flex flex-wrap items-center justify-end gap-2 text-[10px] text-slate-400 sm:text-[11px]">
              <li><Link to="/" className="transition-colors hover:text-white">Home</Link></li>
              <li className="text-slate-600">/</li>
              <li><Link to="/cybersecurity" className="transition-colors hover:text-white">Cybersecurity</Link></li>
              <li className="text-slate-600">/</li>
              <li><Link to="/cybersecurity/identity-access-security" className="transition-colors hover:text-white">Identity & Access Security</Link></li>
              <li className="text-slate-600">/</li>
              <li><span className="font-medium text-[#28B5E1]">Multi-Factor Authentication (MFA)</span></li>
            </ol>
          </nav>
        </div>
      </div>

      <div className="shell relative z-10 flex w-full flex-1 items-center py-10 sm:py-12 lg:py-14">
        <motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.7, ease: "easeOut" }} className="w-full">
          <p className="font-mono text-[11px] font-semibold uppercase tracking-[0.28em] text-[#28B5E1] sm:text-xs">
            Multi-Factor Authentication
          </p>
          <h1 className="mt-4 font-display text-4xl font-bold leading-[1.05] tracking-tight text-white sm:text-5xl md:text-5xl lg:text-[3.5rem]">
            Multi-Factor Authentication <span className="gradient-text">UAE</span>
            <span className="block font-display text-lg font-light leading-tight text-slate-300 sm:text-xl md:text-2xl lg:text-[1.6rem]">
              The highest-ROI control in identity security
            </span>
          </h1>
          <p className="mt-5 max-w-2xl text-sm leading-relaxed text-slate-300 sm:text-base">
            Artiflex IT designs, deploys and manages MFA across the UAE, Oman and Saudi Arabia. Okta, Microsoft Entra MFA, Cisco Duo, RSA SecurID, Yubico and Google Workspace MFA, picked on workload, compliance scope and stack alignment, not vendor preference.
          </p>

          <div className="mt-6 flex flex-wrap items-center gap-3 sm:gap-4">
            <a href="#vendor-matrix" className="inline-flex items-center justify-center gap-2 rounded-full border border-white/20 bg-white/5 px-6 py-3 text-sm font-semibold text-white backdrop-blur-sm transition-all duration-300 hover:border-[#28B5E1]/60 hover:bg-white/10 sm:px-7 sm:py-3.5 sm:text-base">
              Vendor Comparison
            </a>
            <a href="#gartner-comparison" className="inline-flex items-center justify-center gap-2 rounded-full border border-white/20 bg-white/5 px-6 py-3 text-sm font-semibold text-white backdrop-blur-sm transition-all duration-300 hover:border-[#28B5E1]/60 hover:bg-white/10 sm:px-7 sm:py-3.5 sm:text-base">
              Gartner Style Review
            </a>
            <Link to="/blog/origin-identity-access-management" className="group inline-flex items-center justify-center gap-2.5 rounded-full border border-[#28B5E1]/40 bg-[#28B5E1]/10 px-6 py-3 text-sm font-semibold text-[#28B5E1] backdrop-blur-sm transition-all duration-300 hover:border-[#28B5E1] hover:bg-[#28B5E1]/20 hover:text-white sm:px-7 sm:py-3.5 sm:text-base">
              Read Origin Story
              <svg className="h-4 w-4 transition-transform duration-300 group-hover:translate-x-1" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M5 12h14M13 5l7 7-7 7" /></svg>
            </Link>
            <button onClick={openContact} className="group inline-flex items-center justify-center gap-2.5 rounded-full bg-gradient-to-r from-[#045891] to-[#1B8AC7] px-6 py-3 text-sm font-semibold text-white shadow-[0_8px_24px_rgba(27,138,199,0.35)] transition-all duration-300 hover:brightness-110 hover:shadow-[0_12px_32px_rgba(27,138,199,0.5)] sm:px-7 sm:py-3.5 sm:text-base">
              Talk to our Consultant
              <svg className="h-4 w-4 transition-transform duration-300 group-hover:translate-x-1" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M5 12h14M13 5l7 7-7 7" /></svg>
            </button>
          </div>
        </motion.div>
      </div>

      <div className="relative z-10 flex justify-center pb-8">
        <div aria-hidden="true" className="flex flex-col items-center gap-2 font-mono text-[9px] uppercase tracking-[0.32em] text-slate-500">
          <span>Continue</span>
          <span className="h-8 w-px bg-gradient-to-b from-[#28B5E1]/60 to-transparent" />
        </div>
      </div>
    </section>
  );
}

/* ───────── PAGE ───────── */

export default function MfaProduct() {
  const [openLayer, setOpenLayer] = useState<number | null>(0);
  const [activeFaq, setActiveFaq] = useState(0);
  const { open: openContact } = useContactModal();

  return (
    <>
      <>
        <title>Multi-Factor Authentication (MFA) UAE | Push, FIDO2, Passwordless | Artiflex IT</title>
        <meta
          name="description"
          content="Multi-Factor Authentication (MFA) for UAE enterprises. Compare Okta, Microsoft Entra MFA, Cisco Duo, RSA SecurID, Yubico and Google Workspace MFA. Vendor matrix, Gartner-style scorecard, phishing-resistant and passwordless. MFA blocks 99.9% of account attacks."
        />
        <link
          rel="canonical"
          href="https://artiflexit.com/cybersecurity/identity-access-security/mfa"
        />
        <script type="application/ld+json">
          {JSON.stringify({
            "@context": "https://schema.org",
            "@type": "FAQPage",
            mainEntity: faqs.map((f) => ({
              "@type": "Question",
              name: f.question,
              acceptedAnswer: { "@type": "Answer", text: f.answer },
            })),
          })}
        </script>
        <script type="application/ld+json">
          {JSON.stringify({
            "@context": "https://schema.org",
            "@type": "ItemList",
            name: "Recommended MFA Platforms for UAE Businesses",
            itemListElement: vendors.map((v, i) => ({
              "@type": "ListItem",
              position: i + 1,
              name: v.name,
            })),
          })}
        </script>
      </>

      {/* HERO */}
      <MfaHero />

      {/* WHAT IS MFA (INTRO) */}
      <section className="relative overflow-hidden bg-white py-16 sm:py-24">
        <div className="shell">
          <div className="mx-auto max-w-3xl text-center">
            <p className="font-mono text-[11px] font-semibold uppercase tracking-[0.25em] text-[#1B8AC7]">
              Start Here
            </p>
            <h2 className="mt-4 font-display text-3xl font-bold leading-tight text-slate-900 sm:text-4xl">
              What is Multi-Factor Authentication?
            </h2>
            <p className="mt-5 text-base leading-relaxed text-slate-600 sm:text-lg">
              Multi-Factor Authentication (MFA) requires two or more independent proofs of identity
              before access is granted. A password tells you what someone knows. MFA tells you what
              they actually have. That distinction is the difference between an account that gets
              stolen and one that does not, even after the password leaks.
            </p>
          </div>

          <div className="mx-auto mt-10 grid max-w-5xl gap-5 sm:mt-12 md:grid-cols-2">
            <div className="rounded-2xl border border-border-light bg-slate-50 p-6 sm:p-7">
              <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#28B5E1]/10 text-[#1B8AC7]">
                <AlertTriangleIcon className="h-6 w-6" />
              </div>
              <h3 className="mt-4 font-display text-lg font-bold text-slate-900">
                Why does an organisation need MFA?
              </h3>
              <p className="mt-3 text-sm leading-relaxed text-slate-600 sm:text-base">
                Passwords get reused, phished, keylogged, and leaked in third-party breaches. Once a
                password is compromised, the attacker has everything they need to impersonate the
                user. MFA breaks that chain by requiring a second, independent factor, which is why
                Microsoft reports it blocks 99.9 percent of automated account compromise attacks. It
                is the single highest-ROI security investment available, and a baseline expectation
                under NESA, PDPL and CBUAE.
              </p>
            </div>
            <div className="rounded-2xl border border-border-light bg-slate-50 p-6 sm:p-7">
              <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#28B5E1]/10 text-[#1B8AC7]">
                <GearIcon className="h-6 w-6" />
              </div>
              <h3 className="mt-4 font-display text-lg font-bold text-slate-900">
                How Artiflex approaches it
              </h3>
              <p className="mt-3 text-sm leading-relaxed text-slate-600 sm:text-base">
                We start with your stack, your audit scope, and the accounts you have to protect,
                then map the right factor mix to the requirement. For Microsoft-aligned estates we
                recommend{" "}
                <strong className="font-semibold text-slate-900">Microsoft Entra MFA</strong> with
                Conditional Access, complemented by Okta, Cisco Duo or FIDO2 hardware keys where the
                workload and risk profile demand it.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* ───────── WHAT MFA COVERS (BUILDING BLOCKS) ───────── */}
      <section className="relative overflow-hidden bg-slate-50 py-16 sm:py-24">
        <div className="shell">
          <div className="mx-auto max-w-3xl text-center">
            <p className="font-mono text-[11px] font-semibold uppercase tracking-[0.25em] text-[#1B8AC7]">
              The Building Blocks
            </p>
            <h2 className="mt-4 font-display text-3xl font-bold leading-tight text-slate-900 sm:text-4xl">
              What MFA covers
            </h2>
            <p className="mt-5 text-base leading-relaxed text-slate-600 sm:text-lg">
              MFA is not a single product or a single factor. It is a set of complementary methods,
              from push and TOTP to phishing-resistant keys and adaptive policy, that can be adopted
              together or layered by risk. Here is what each capability does, and what to look for.
            </p>
          </div>

          <div className="mt-12 grid gap-5 sm:mt-16 sm:grid-cols-2 lg:grid-cols-3">
            {mfaBuildingBlocks.map((b) => {
              const Icon = b.icon;
              return (
                <div
                  key={b.title}
                  className="group rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition-all duration-300 hover:-translate-y-1 hover:border-[#28B5E1]/40 hover:shadow-md"
                >
                  <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#28B5E1]/10 text-[#1B8AC7] transition-colors group-hover:bg-[#28B5E1]/20">
                    <Icon className="h-6 w-6" />
                  </div>
                  <h3 className="mt-4 font-display text-lg font-bold text-slate-900">{b.title}</h3>
                  <ul className="mt-3 space-y-2">
                    {b.points.map((pt) => (
                      <li key={pt} className="flex gap-2.5 text-sm leading-relaxed text-slate-600">
                        <span aria-hidden className="mt-[7px] h-1.5 w-1.5 shrink-0 rounded-[3px] bg-[#1B8AC7]" />
                        <span>{pt}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* ───────── MFA METHODS (DARK CARDS) ───────── */}
      <section className="relative overflow-hidden bg-slate-50 pb-16 sm:pb-24">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_bottom_right,rgba(27,138,199,0.06),transparent_60%)]" />
        <div className="shell relative">
          <div className="mx-auto max-w-3xl text-center">
            <p className="font-mono text-[11px] font-semibold uppercase tracking-[0.25em] text-[#1B8AC7]">
              MFA Methods
            </p>
            <h2 className="mt-4 font-display text-3xl font-bold leading-tight text-slate-900 sm:text-4xl">
              Not all second factors are equal
            </h2>
            <p className="mt-5 text-base leading-relaxed text-slate-600 sm:text-lg">
              From convenient push to phishing-resistant hardware keys, each factor sits at a
              different point on the security and usability curve. The right MFA programme blends them
              by account risk.
            </p>
          </div>

          <div className="mt-12 grid grid-cols-1 gap-5 md:grid-cols-2">
            {methods.map((m, idx) => {
              const Icon = m.icon;
              return (
                <motion.article
                  key={m.title}
                  initial={{ opacity: 0, y: 18 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true, margin: "-60px" }}
                  transition={{ duration: 0.5, delay: idx * 0.04 }}
                  className="group relative overflow-hidden rounded-2xl border border-white/10 bg-gradient-to-br from-[#04101E] via-[#06182B] to-[#0A3D6B] p-7 shadow-lg shadow-slate-900/15 transition-all duration-300 hover:-translate-y-1 hover:border-white/25 hover:shadow-xl hover:shadow-slate-900/25 sm:p-8"
                >
                  <span
                    aria-hidden="true"
                    className="absolute inset-x-0 top-0 h-1 bg-gradient-to-r from-[#28B5E1] to-[#1B8AC7]"
                  />
                  <div className="mb-5 inline-flex h-12 w-12 items-center justify-center rounded-xl bg-[#28B5E1]/15 text-[#28B5E1]">
                    <Icon className="h-6 w-6" />
                  </div>
                  <h3 className="font-display text-xl font-bold text-white">
                    {m.title}
                  </h3>
                  <p className="mt-3 text-sm leading-relaxed text-slate-300">
                    {m.desc}
                  </p>
                  <span className="mt-5 inline-flex items-center rounded-full border border-[#28B5E1]/30 bg-[#28B5E1]/10 px-2.5 py-0.5 font-mono text-[10px] font-semibold uppercase tracking-[0.22em] text-[#28B5E1]">
                    {m.tag}
                  </span>
                </motion.article>
              );
            })}
          </div>
        </div>
      </section>

      {/* ───────── MFA VENDORS WE DELIVER (HONEYCOMB) ───────── */}
      <section className="relative overflow-hidden bg-slate-50 py-16 sm:py-20">
        <div
          aria-hidden="true"
          className="pointer-events-none absolute inset-0 opacity-[0.05]"
          style={{
            backgroundImage:
              "linear-gradient(to right, #1B8AC7 1px, transparent 1px), linear-gradient(to bottom, #1B8AC7 1px, transparent 1px)",
            backgroundSize: "48px 48px",
          }}
        />
        <div
          aria-hidden="true"
          className="pointer-events-none absolute -left-24 top-1/2 h-72 w-72 -translate-y-1/2 rounded-full bg-[#1B8AC7]/10 blur-3xl"
        />
        <div
          aria-hidden="true"
          className="pointer-events-none absolute -right-24 top-1/3 h-72 w-72 rounded-full bg-[#28B5E1]/10 blur-3xl"
        />

        <div className="shell relative">
          <div className="mx-auto max-w-3xl text-center">
            <p className="font-mono text-[11px] font-semibold uppercase tracking-[0.25em] text-[#1B8AC7]">
              The Vendor Lineup
            </p>
            <h2 className="mt-4 font-display text-3xl font-bold leading-tight text-slate-900 sm:text-4xl lg:text-[2.5rem]">
              MFA{" "}
              <span className="bg-gradient-to-r from-[#1B8AC7] to-[#28B5E1] bg-clip-text text-transparent">
                Vendors
              </span>{" "}
              we deliver
            </h2>
            <p className="mt-5 text-base leading-relaxed text-slate-600 sm:text-lg">
              The Multi-Factor Authentication platforms we design, deploy and manage across UAE environments. The conversation starts with your stack, your audit scope, and the accounts you have to protect.
            </p>
          </div>

          <div className="mt-14 hidden flex-col items-center lg:flex">
            {(() => {
              const layouts: Record<number, number[]> = {
                1: [1], 2: [2], 3: [3], 4: [3, 1], 5: [3, 2],
                6: [3, 3], 7: [4, 3], 8: [4, 4], 9: [5, 4],
                10: [5, 5], 11: [6, 5], 12: [6, 6],
              };
              const sizes =
                layouts[vendorLineup.length] ??
                [Math.ceil(vendorLineup.length / 2), Math.floor(vendorLineup.length / 2)];
              const rows: typeof vendorLineup[] = [];
              let i = 0;
              sizes.forEach((s) => {
                rows.push(vendorLineup.slice(i, i + s));
                i += s;
              });
              const HEX_PATH =
                "polygon(50% 0%, 100% 25%, 100% 75%, 50% 100%, 0% 75%, 0% 25%)";
              return rows.map((row, rowIdx) => (
                <div
                  key={rowIdx}
                  className="flex"
                  style={{
                    marginTop: rowIdx === 0 ? 0 : -52,
                    transform:
                      rowIdx > 0 && rows[rowIdx - 1].length === row.length
                        ? "translateX(90px)"
                        : undefined,
                  }}
                >
                  {row.map((v) => (
                    <Link
                      key={v.slug}
                      to={`/cybersecurity/mfa/${v.slug}`}
                      aria-label={v.name}
                      className="group relative block h-[208px] w-[180px] transition-all duration-300 hover:z-10 hover:scale-[1.06] [filter:drop-shadow(0_4px_12px_rgba(15,23,42,0.10))] hover:[filter:drop-shadow(0_10px_30px_rgba(40,181,225,0.45))]"
                    >
                      <div
                        className="absolute inset-0 bg-slate-200/80 transition-colors duration-300 group-hover:bg-[#28B5E1]"
                        style={{ clipPath: HEX_PATH }}
                      />
                      <div
                        className="absolute inset-[2px] bg-white transition-all duration-300 group-hover:bg-gradient-to-b group-hover:from-[#28B5E1]/[0.08] group-hover:to-white"
                        style={{ clipPath: HEX_PATH }}
                      />
                      <div className="relative flex h-full flex-col items-center justify-center px-5 text-center">
                        {v.logo ? (
                          <img
                            src={v.logo}
                            alt={v.name}
                            loading="lazy"
                            className="h-20 w-20 object-contain transition-transform duration-300 group-hover:scale-110"
                          />
                        ) : (
                          <span className="px-2 text-center font-display text-sm font-semibold leading-tight text-slate-900">
                            {v.name}
                          </span>
                        )}
                      </div>
                    </Link>
                  ))}
                </div>
              ));
            })()}
          </div>

          <div className="mt-12 grid grid-cols-2 gap-3 sm:grid-cols-3 sm:gap-4 lg:hidden">
            {vendorLineup.map((v) => (
              <Link
                key={v.slug}
                to={`/cybersecurity/mfa/${v.slug}`}
                className="group flex flex-col items-center justify-center rounded-2xl border border-slate-200 bg-white p-4 text-center shadow-sm transition-all duration-300 hover:-translate-y-0.5 hover:border-[#28B5E1]/50 hover:shadow-md"
              >
                {v.logo ? (
                  <img
                    src={v.logo}
                    alt={v.name}
                    loading="lazy"
                    onError={(e) => {
                      const img = e.currentTarget as HTMLImageElement;
                      img.style.display = "none";
                      const fb = img.nextElementSibling as HTMLElement | null;
                      if (fb) fb.style.removeProperty("display");
                    }}
                    className="h-12 w-12 object-contain"
                  />
                ) : null}
                <p
                  className="font-display text-[11px] font-semibold leading-tight text-slate-900"
                  style={{ display: v.logo ? "none" : "block" }}
                >
                  {v.name}
                </p>
              </Link>
            ))}
          </div>

          <p className="mt-12 text-center text-sm text-slate-500">
            <span className="font-semibold text-slate-700">
              {vendorLineup.length} platforms
            </span>
            , picked by stack alignment, compliance scope, and account risk.
          </p>
        </div>
      </section>

      {/* ───────── MFA ASSURANCE LADDER ───────── */}
      <section className="relative overflow-hidden bg-slate-50 py-16 sm:py-24">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_top,rgba(27,138,199,0.06),transparent_60%)]" />
        <div className="shell relative">
          <div className="mx-auto max-w-3xl text-center">
            <p className="font-mono text-xs font-semibold uppercase tracking-[0.25em] text-[#1B8AC7]">
              How MFA Works
            </p>
            <h2 className="mt-4 font-display text-3xl font-bold leading-tight text-slate-900 sm:text-4xl">
              The MFA Assurance Ladder
            </h2>
            <p className="mt-5 text-base leading-relaxed text-slate-600 sm:text-lg">
              MFA is not all-or-nothing. It is a ladder of assurance where each rung blocks a larger share of attacks than the one below. The goal is to climb it deliberately, with the strongest factors on your highest-risk accounts.
            </p>
          </div>

          <div className="mt-12 grid items-start gap-4 sm:mt-16 sm:gap-5 md:grid-cols-3">
            {mfaLadder.map((l, idx) => {
              const isOpen = openLayer === idx;
              const Icon = l.icon;
              return (
                <div
                  key={l.title}
                  tabIndex={0}
                  onMouseEnter={() => setOpenLayer(idx)}
                  onMouseLeave={() =>
                    setOpenLayer((prev) => (prev === idx ? null : prev))
                  }
                  onFocus={() => setOpenLayer(idx)}
                  onBlur={() =>
                    setOpenLayer((prev) => (prev === idx ? null : prev))
                  }
                  onClick={() =>
                    setOpenLayer((prev) => (prev === idx ? null : idx))
                  }
                  className="group relative cursor-pointer overflow-hidden rounded-2xl border border-slate-200 bg-white p-4 shadow-sm outline-none transition-all duration-300 hover:-translate-y-1 hover:border-[#28B5E1]/40 hover:shadow-md focus-visible:ring-2 focus-visible:ring-[#28B5E1]/40 sm:p-5"
                >
                  <div className="flex items-center justify-between gap-2">
                    <span className="rounded-full border border-[#1B8AC7]/20 bg-[#1B8AC7]/[0.06] px-2.5 py-0.5 font-mono text-[10px] font-semibold uppercase tracking-[0.18em] text-[#1B8AC7]">
                      {l.tag}
                    </span>
                  </div>
                  <div className="mt-3 flex items-start gap-3">
                    <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-[#28B5E1]/10 text-[#1B8AC7]">
                      <Icon className="h-5 w-5" />
                    </div>
                    <div className="min-w-0">
                      <h3 className="font-display text-base font-semibold text-slate-900 sm:text-lg">
                        {l.title}
                      </h3>
                      <p className="mt-0.5 text-[12px] italic text-slate-500">
                        {l.desc}
                      </p>
                    </div>
                  </div>

                  <AnimatePresence initial={false}>
                    {isOpen && (
                      <motion.div
                        key="content"
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: "auto", opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        transition={{ duration: 0.4, ease: [0.16, 1, 0.3, 1] }}
                        className="overflow-hidden"
                      >
                        <p className="mt-4 border-t border-slate-200 pt-3 text-xs leading-relaxed text-slate-600">
                          {l.details}
                        </p>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* ───────── PRINCIPLE QUOTE ───────── */}
      <section className="relative bg-slate-50 pb-16 sm:pb-24">
        <div className="shell">
          <div className="relative overflow-hidden rounded-2xl border border-white/10 bg-gradient-to-br from-[#04101E] via-[#06182B] to-[#0A3D6B] p-8 shadow-lg shadow-slate-900/15 sm:p-12">
            <span
              aria-hidden="true"
              className="absolute inset-y-0 left-0 w-1 bg-gradient-to-b from-[#28B5E1] to-[#1B8AC7]"
            />
            <span
              aria-hidden="true"
              className="absolute -left-2 -top-4 font-display text-7xl font-bold leading-none text-[#28B5E1]/20 sm:-left-3 sm:-top-6 sm:text-8xl"
            >
              &ldquo;
            </span>
            <blockquote className="relative">
              <p className="font-display text-xl italic leading-snug text-white sm:text-2xl md:text-[1.75rem]">
                {quote.text}
              </p>
              <footer className="mt-6 flex items-center gap-3">
                <span aria-hidden="true" className="h-px w-8 bg-[#28B5E1]" />
                <span className="font-mono text-[10px] font-semibold uppercase tracking-[0.22em] text-[#28B5E1] sm:text-[11px]">
                  {quote.attribution}
                </span>
              </footer>
            </blockquote>
          </div>
        </div>
      </section>

      {/* ───────── VENDOR COMPARISON FOR MFA BUYERS ───────── */}
      <section
        id="vendor-matrix"
        className="relative bg-white py-16 scroll-mt-20 sm:py-24"
      >
        <div className="shell">
          <div className="mb-10 text-center sm:mb-12 md:mb-16">
            <h2 className="mx-auto max-w-3xl font-display text-2xl font-bold tracking-tight text-heading sm:text-3xl md:text-4xl lg:text-[2.75rem] lg:leading-[1.15]">
              Vendor comparison for{" "}
              <span className="gradient-text">MFA buyers</span>
            </h2>
            <p className="mx-auto mt-3 max-w-2xl text-sm leading-relaxed text-body sm:mt-5 sm:text-base lg:text-lg">
              MFA is not just about adding a second factor, it is about choosing the factor that fits your environment, your risk profile, and your users. Artiflex suggests the solution that best fits your needs.
            </p>
          </div>

          <div className="mt-8 flex justify-center sm:mt-10">
            <button
              onClick={openContact}
              className="group inline-flex items-center justify-center gap-2.5 rounded-full bg-gradient-to-r from-[#045891] to-[#1B8AC7] px-6 py-3 text-sm font-semibold text-white shadow-[0_8px_24px_rgba(27,138,199,0.35)] transition-all duration-300 hover:brightness-110 hover:shadow-[0_12px_32px_rgba(27,138,199,0.5)] sm:px-7 sm:py-3.5 sm:text-base"
            >
              Talk to our Consultant
              <svg
                className="h-4 w-4 transition-transform duration-300 group-hover:translate-x-1"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
                aria-hidden="true"
              >
                <path d="M5 12h14M13 5l7 7-7 7" />
              </svg>
            </button>
          </div>

          <div className="mt-12 overflow-hidden rounded-2xl border border-[#0A3D6B]/40 bg-white shadow-[0_10px_40px_-12px_rgba(15,23,42,0.12)]">
            <div className="overflow-x-auto">
              <table className="w-full table-fixed border-collapse text-center text-sm" style={{ minWidth: Math.max(640, 150 + matrixVendors.length * 116) }}>
                <thead>
                  <tr className="bg-gradient-to-r from-[#045891] to-[#1B8AC7]">
                    <th className="sticky left-0 z-10 w-[18%] bg-[#045891] px-2 py-3 sm:px-4 sm:py-5 align-bottom font-mono text-[10px] font-semibold uppercase tracking-[0.22em] text-[#9CD6EE]">
                      Criteria
                    </th>
                    {matrixVendors.map((v) => (
                      <th
                        key={v.name}
                        className="border-l border-white/15 px-2 py-3 sm:px-4 sm:py-5 align-bottom"
                      >
                        {v.recommended && (
                          <span className="mb-1.5 inline-flex items-center gap-1 rounded-full border border-emerald-300/40 bg-emerald-400/20 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider text-emerald-100">
                            ✓ Recommended
                          </span>
                        )}
                        <p className="font-display text-sm font-semibold text-white sm:text-base">
                          {v.name}
                        </p>
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {matrixRows.map((row, rIdx) => (
                    <tr
                      key={row.label}
                      className={`transition-colors ${
                        row.type === "verdict"
                          ? "border-t-2 border-[#28B5E1]/30 bg-gradient-to-r from-[#04101E] to-[#0A3D6B]"
                          : `border-t border-[#0A3D6B]/20 hover:bg-[#28B5E1]/[0.04] ${
                              rIdx % 2 === 0 ? "bg-white" : "bg-slate-50/60"
                            }`
                      }`}
                    >
                      <th
                        scope="row"
                        className={`sticky left-0 z-10 px-2 py-3 align-middle sm:px-4 sm:py-4 font-display text-sm font-semibold ${
                          row.type === "verdict"
                            ? "bg-[#04101E] uppercase tracking-wider text-[#28B5E1]"
                            : `${rIdx % 2 === 0 ? "bg-white" : "bg-slate-50"} text-slate-900`
                        }`}
                      >
                        {row.label}
                      </th>
                      {row.cells.map((cell, cIdx) => (
                        <td
                          key={cIdx}
                          className={`px-4 py-4 align-middle ${
                            row.type === "verdict"
                              ? "border-l border-white/10 text-slate-300"
                              : "border-l border-[#0A3D6B]/20 text-slate-700"
                          }`}
                        >
                          {row.type === "stars" ? (
                            <div>
                              <span aria-label={`${(cell as StarCell).stars} out of 5`} className="text-amber-500">
                                {"★".repeat((cell as StarCell).stars)}
                                <span className="text-slate-300">
                                  {"★".repeat(5 - (cell as StarCell).stars)}
                                </span>
                              </span>
                              <p className="mt-1 text-xs leading-snug text-slate-600">
                                {(cell as StarCell).note}
                              </p>
                            </div>
                          ) : row.type === "verdict" ? (
                            <div className="space-y-1.5">
                              {(cell as VerdictCell).recommended && (
                                <span className="inline-flex items-center gap-1 rounded-full border border-emerald-400/30 bg-emerald-500/15 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider text-emerald-300">
                                  ✓ Recommended
                                </span>
                              )}
                              <p className="text-xs leading-relaxed text-slate-300">
                                {(cell as VerdictCell).text}
                              </p>
                            </div>
                          ) : (
                            <p className="text-xs leading-snug text-slate-700">
                              {cell as string}
                            </p>
                          )}
                        </td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </section>

      {/* ───────── DETAILED VENDOR CARDS + GARTNER SCORECARD ───────── */}
      <section className="relative bg-slate-50 py-16 sm:py-24">
        <div className="shell">
          <div className="mx-auto max-w-4xl text-center">
            <h2 className="font-display text-3xl font-bold leading-tight text-slate-900 sm:text-4xl">
              Detailed Comparison on MFA Vendors
            </h2>
            <p className="mt-5 text-base leading-relaxed text-slate-600 sm:text-lg">
              Strengths, blind spots, and the buyer profile each vendor was built for. Recommendations are based on UAE deployment patterns, not vendor tier.
            </p>
          </div>

          <div className="mt-6 flex justify-center sm:mt-8">
            <button
              onClick={openContact}
              className="group inline-flex items-center justify-center gap-2.5 rounded-full bg-gradient-to-r from-[#045891] to-[#1B8AC7] px-6 py-3 text-sm font-semibold text-white shadow-[0_8px_24px_rgba(27,138,199,0.35)] transition-all duration-300 hover:brightness-110 hover:shadow-[0_12px_32px_rgba(27,138,199,0.5)] sm:px-7 sm:py-3.5 sm:text-base"
            >
              Talk to our Consultant
              <svg
                className="h-4 w-4 transition-transform duration-300 group-hover:translate-x-1"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
                aria-hidden="true"
              >
                <path d="M5 12h14M13 5l7 7-7 7" />
              </svg>
            </button>
          </div>

          <div className="mx-auto mt-12 grid max-w-6xl gap-6 sm:mt-16 lg:grid-cols-2 lg:items-stretch">
            {vendors.map((v, idx) => {
              const recommended = v.best.includes("Recommended");
              return (
                <motion.div
                  key={v.name}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true, margin: "-60px" }}
                  transition={{ duration: 0.5, delay: idx * 0.05 }}
                  className="flex h-full"
                >
                  <Link
                    to={`/cybersecurity/mfa/${v.slug}`}
                    aria-label={`View details for ${v.name}`}
                    className={`group relative flex h-full w-full flex-col overflow-hidden rounded-2xl border bg-white p-6 transition-all duration-300 hover:-translate-y-0.5 hover:shadow-[0_12px_40px_rgba(4,88,145,0.12)] sm:p-8 ${
                      recommended
                        ? "border-brand-blue/30 shadow-[0_4px_20px_rgba(27,138,199,0.10)]"
                        : "border-border-light shadow-[0_1px_3px_rgba(0,0,0,0.04)] hover:border-brand-blue/25"
                    }`}
                  >
                    {recommended && (
                      <span
                        className="absolute -top-px left-6 inline-flex rounded-b-md bg-brand-blue px-3 py-1 font-mono text-[10px] font-semibold uppercase tracking-[0.2em] text-white"
                        aria-label="Recommended vendor"
                      >
                        Recommended
                      </span>
                    )}

                    <div className="flex items-start justify-between gap-4 pt-3">
                      <div className="min-w-0">
                        <h3 className="font-display text-xl font-bold text-heading transition-colors group-hover:text-brand-blue sm:text-2xl">
                          {v.name}
                        </h3>
                        <p className="mt-1 text-xs font-semibold uppercase tracking-[0.15em] text-brand-blue">
                          {v.best}
                        </p>
                      </div>
                      <img
                        src={v.logo}
                        alt={`${v.name} logo`}
                        loading="lazy"
                        onError={(e) => {
                          (e.currentTarget as HTMLImageElement).style.display = "none";
                        }}
                        className="h-10 w-24 shrink-0 object-contain object-right sm:h-12 sm:w-32"
                      />
                    </div>

                    <div className="mt-5 space-y-3">
                      <div>
                        <p className="font-mono text-[10px] font-semibold uppercase tracking-[0.2em] text-muted">
                          Why it wins
                        </p>
                        <p className="mt-1.5 text-sm leading-relaxed text-body">
                          {v.strength}
                        </p>
                      </div>
                      <div>
                        <p className="font-mono text-[10px] font-semibold uppercase tracking-[0.2em] text-muted">
                          Consider
                        </p>
                        <p className="mt-1.5 text-sm leading-relaxed text-body/80">
                          {v.watch}
                        </p>
                      </div>
                    </div>

                    <span className="mt-auto inline-flex items-center gap-1.5 pt-6 text-xs font-semibold text-brand-blue transition-all group-hover:gap-2.5 sm:text-sm">
                      View {v.name.split(" ")[0]} details
                      <span aria-hidden="true">→</span>
                    </span>
                  </Link>
                </motion.div>
              );
            })}
          </div>

          <div className="mx-auto mt-12 max-w-5xl rounded-3xl border border-white/10 bg-gradient-to-br from-[#0A3D6B] via-[#04101E] to-[#020617] p-8 text-center shadow-xl shadow-[#1B8AC7]/10 sm:p-12">
            <p className="text-base leading-relaxed text-slate-300 sm:text-lg md:text-xl">
              <span className="font-semibold text-white">Artiflex IT delivers Okta, Microsoft Entra MFA, Cisco Duo, RSA SecurID, Yubico and Google Workspace MFA</span> <span className="text-white">across UAE MFA programmes.</span> <br />
              <span className="text-xs italic text-white sm:text-base">The vendor follows the assessment, not the other way around.</span>
            </p>
          </div>

          {/* Feature ratings */}
          <div id="gartner-comparison" className="mx-auto mt-20 max-w-4xl scroll-mt-24 text-center sm:mt-28">
            <h2 className="font-display text-3xl font-bold leading-tight text-slate-900 sm:text-4xl">
              Gartner-style Capability Comparison
            </h2>
            <p className="mt-5 text-base leading-relaxed text-slate-600 sm:text-lg">
              Each vendor is rated across MFA capabilities using a standardised tier scale. A gold ★ marker denotes best-in-class performance for that specific capability.
            </p>
          </div>

          <div className="mt-12 overflow-hidden rounded-2xl border border-[#0A3D6B]/40 bg-white shadow-[0_10px_40px_-12px_rgba(15,23,42,0.12)]">
            <div className="overflow-x-auto">
              <table className="w-full table-fixed border-collapse text-center text-sm" style={{ minWidth: Math.max(640, 150 + featureVendors.length * 116) }}>
                <thead>
                  <tr className="bg-gradient-to-r from-[#045891] to-[#1B8AC7]">
                    <th className="sticky left-0 z-10 w-[18%] bg-[#045891] px-2 py-3 sm:px-4 sm:py-5 align-bottom font-mono text-[10px] font-semibold uppercase tracking-[0.22em] text-[#9CD6EE]">
                      Capability
                    </th>
                    {featureVendors.map((v) => (
                      <th
                        key={v}
                        className="border-l border-white/15 px-2 py-3 sm:px-4 sm:py-5 align-bottom font-display text-sm font-semibold text-white sm:text-base"
                      >
                        {v}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {featureRows.map((row, rIdx) => (
                    <tr
                      key={row.label}
                      className={`border-t border-[#0A3D6B]/20 transition-colors hover:bg-[#28B5E1]/[0.04] ${
                        rIdx % 2 === 0 ? "bg-white" : "bg-slate-50/60"
                      }`}
                    >
                      <th
                        scope="row"
                        className={`sticky left-0 z-10 px-2 py-3 align-middle sm:px-4 sm:py-4 font-display text-sm font-semibold text-slate-900 ${
                          rIdx % 2 === 0 ? "bg-white" : "bg-slate-50"
                        }`}
                      >
                        {row.label}
                      </th>
                      {row.cells.map((cell, cIdx) => {
                        const t = tierStyles[cell.tier];
                        return (
                          <td
                            key={cIdx}
                            className="border-l border-[#0A3D6B]/20 px-2 py-3 sm:px-4 sm:py-4 align-middle"
                          >
                            <span
                              className={`inline-flex items-center gap-1 rounded-md px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider ${t.bg} ${t.text}`}
                            >
                              {cell.tier === "best" && <span aria-hidden="true">★</span>}
                              {t.label}
                            </span>
                            <p className="mt-1.5 text-xs leading-snug text-slate-600">
                              {cell.note}
                            </p>
                          </td>
                        );
                      })}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Legend */}
          <div className="mx-auto mt-8 flex max-w-4xl flex-wrap items-center justify-center gap-3 text-xs text-slate-600">
            <span className="font-mono uppercase tracking-wider text-slate-500">Rating scale:</span>
            {(["best", "excellent", "veryStrong", "strong", "good"] as Tier[]).map((t) => {
              const s = tierStyles[t];
              return (
                <span
                  key={t}
                  className={`inline-flex items-center gap-1 rounded-md px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider ${s.bg} ${s.text}`}
                >
                  {t === "best" && <span aria-hidden="true">★</span>}
                  {s.label}
                </span>
              );
            })}
          </div>
        </div>
      </section>

      {/* ───────── DECISION GUIDE ───────── */}
      <section className="relative overflow-hidden bg-slate-50 py-16 sm:py-24">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_bottom,rgba(27,138,199,0.06),transparent_60%)]" />
        <div className="shell relative">
          <div className="mx-auto max-w-3xl text-center">
            <p className="font-mono text-xs font-semibold uppercase tracking-[0.25em] text-[#1B8AC7]">
              Decision Guide
            </p>
            <h2 className="mt-4 font-display text-3xl font-bold leading-tight text-slate-900 sm:text-4xl">
              How to choose your MFA platform
            </h2>
            <p className="mt-5 text-base leading-relaxed text-slate-600 sm:text-lg">
              Vendor selection rarely comes down to a single capability. The right platform depends on where your identities live today, which clouds you bet on, and which accounts carry the most risk.
            </p>
          </div>

          {/* Framing questions */}
          <div className="mx-auto mt-10 max-w-5xl sm:mt-12">
            <div className="rounded-2xl border border-white/10 bg-gradient-to-br from-[#04101E] via-[#06182B] to-[#0A3D6B] p-6 shadow-lg sm:p-8">
              <p className="font-mono text-[11px] font-semibold uppercase tracking-[0.25em] text-[#28B5E1]">
                Start with these questions
              </p>
              <h3 className="mt-3 font-display text-xl font-bold text-white sm:text-2xl">
                Before you compare products, get clear on your requirement
              </h3>
              <ul className="mt-5 grid gap-3 sm:grid-cols-2">
                {[
                  "What is your expectation out of MFA, what business or compliance problem are you trying to solve?",
                  "Are you rolling MFA out for all users, or starting with privileged and executive accounts only?",
                  "Where do your identities live today, Active Directory, Entra ID, Okta, or multiple clouds?",
                  "Which regulations apply to you (NESA, PDPL, CBUAE, ISO 27001) and what evidence do you need?",
                  "Do you need phishing-resistant factors, passwordless, or only a basic second factor today?",
                  "What is your timeline, budget envelope, and tolerance for user friction during rollout?",
                ].map((q) => (
                  <li
                    key={q}
                    className="flex items-start gap-3 rounded-xl border border-white/5 bg-white/[0.03] px-4 py-3"
                  >
                    <span aria-hidden="true" className="mt-0.5 font-mono text-sm font-bold text-[#28B5E1]">
                      ?
                    </span>
                    <span className="text-sm leading-relaxed text-slate-200">{q}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* Requirement-based recommendation summary */}
          <div className="mx-auto mt-6 max-w-5xl">
            <div className="rounded-2xl border border-border-light bg-white p-6 shadow-[0_1px_3px_rgba(0,0,0,0.04)] sm:p-8">
              <h3 className="font-display text-xl font-bold text-slate-900 sm:text-2xl">
                How Artiflex recommends, your requirement decides, not the vendor
              </h3>
              <p className="mt-3 text-sm leading-relaxed text-slate-600 sm:text-base">
                Our product recommendation is based purely on what each customer actually needs.
                Whether you want MFA across your whole estate or phishing-resistant keys for your
                highest-risk accounts, we map the right factor mix to your requirement.
              </p>
              <div className="mt-6 grid gap-4 md:grid-cols-3">
                <div className="rounded-xl border border-border-light bg-slate-50 p-5">
                  <p className="font-mono text-[11px] font-semibold uppercase tracking-wider text-[#1B8AC7]">
                    Estate-wide MFA
                  </p>
                  <p className="mt-2 text-sm leading-relaxed text-slate-600">
                    If you want MFA across every user and application with conditional access policy,
                    we design the full rollout and select the platform mix that fits your estate and
                    compliance scope.
                  </p>
                </div>
                <div className="rounded-xl border border-emerald-200 bg-emerald-50/60 p-5">
                  <p className="font-mono text-[11px] font-semibold uppercase tracking-wider text-emerald-700">
                    Phishing-resistant
                  </p>
                  <p className="mt-2 text-sm leading-relaxed text-slate-700">
                    If your priority is defeating real-time phishing for privileged and executive
                    accounts, FIDO2 hardware keys and passkeys are the answer. We scope and deploy
                    them as a layer on your existing platform.
                  </p>
                </div>
                <div className="rounded-xl border border-emerald-200 bg-emerald-50/60 p-5">
                  <p className="font-mono text-[11px] font-semibold uppercase tracking-wider text-emerald-700">
                    Broader IAM
                  </p>
                  <p className="mt-2 text-sm leading-relaxed text-slate-700">
                    If MFA is one part of a wider identity programme, see our{" "}
                    <Link
                      to="/cybersecurity/identity-access-security/iam"
                      className="font-semibold text-[#1B8AC7] underline-offset-2 hover:underline"
                    >
                      Identity & Access Management (IAM)
                    </Link>{" "}
                    page for the full picture and vendor selection.
                  </p>
                </div>
              </div>
            </div>
          </div>

          <div className="mx-auto mt-10 max-w-6xl sm:mt-12">
            <div className="grid grid-cols-1 gap-2 sm:gap-3 md:grid-cols-2">
              {decisionGuide.map((row) => (
                <div
                  key={row.scenario}
                  tabIndex={0}
                  className="group relative flex min-h-[5rem] flex-col justify-center overflow-hidden rounded-xl border border-white/10 bg-gradient-to-r from-[#04101E] to-[#0A3D6B] px-4 py-3 shadow-md transition-all duration-300 hover:border-[#28B5E1]/40 hover:shadow-lg focus-within:border-[#28B5E1]/40 focus:outline-none focus-visible:ring-2 focus-visible:ring-[#28B5E1]/40 sm:min-h-[5.5rem] sm:px-5 sm:py-3.5"
                >
                  <div className="flex items-center justify-between gap-3">
                    <h4 className="font-display text-sm font-semibold leading-snug text-white sm:text-base">
                      {row.scenario}
                    </h4>
                    <svg
                      aria-hidden="true"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth={2}
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      className="h-4 w-4 shrink-0 text-[#28B5E1] transition-transform duration-300 group-hover:rotate-180 group-focus-within:rotate-180"
                    >
                      <polyline points="6 9 12 15 18 9" />
                    </svg>
                  </div>
                  <div className="grid grid-rows-[0fr] transition-[grid-template-rows] duration-300 ease-out group-hover:grid-rows-[1fr] group-focus-within:grid-rows-[1fr]">
                    <div className="overflow-hidden">
                      <p className="mt-2 text-xs leading-relaxed text-slate-300 sm:text-sm">
                        {row.recommend}
                      </p>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ───────── OUR DELIVERY MODEL ───────── */}
      <section className="relative bg-surface-secondary py-16 sm:py-24">
        <div className="shell">
          <SectionHeader
            label="How we work"
            title={
              <>
                Our <span className="gradient-text">delivery model</span>
              </>
            }
            description="We don't sell licences, we deliver MFA outcomes: assess, design, deploy, manage. Every stage produces something an auditor can read and a CFO can sign off on."
            centered
          />

          <div className="mt-12 grid gap-4 sm:mt-16 sm:gap-5 lg:grid-cols-4">
            {[
              {
                title: "Assess",
                duration: "2 weeks",
                summary:
                  "Inventory of users, applications, and existing authentication methods. Audit of password exposure, push-fatigue risk, legacy protocol usage, and phishing-resistant readiness.",
                deliverable:
                  "Current-state report, vendor recommendation with rationale, three-year TCO comparison.",
              },
              {
                title: "Design",
                duration: "2 to 3 weeks",
                summary:
                  "Factor strategy for your environment: conditional access policy framework, adaptive risk rules, phishing-resistant scope for privileged accounts, and rollout sequencing by risk tier.",
                deliverable:
                  "Approved policy design, signed-off rollout sequence, change-management plan.",
              },
              {
                title: "Deploy",
                duration: "4 to 10 weeks",
                summary:
                  "Phased enrolment with rollback at every stage. Privileged accounts first, then workforce, then legacy and service accounts. Production cutover with day-1 hypercare.",
                deliverable:
                  "Live MFA enforcement, audit-ready documentation, runbooks for your team.",
              },
              {
                title: "Manage",
                duration: "Ongoing",
                summary:
                  "24/7 monitoring, policy change management, push-fatigue and risk-event review, token and key lifecycle, monthly board-readable reporting, quarterly policy reviews.",
                deliverable:
                  "Operational MFA with SLAs you can rely on. Or a clean handover to your team.",
              },
            ].map((s, idx) => (
              <motion.div
                key={s.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-60px" }}
                transition={{ duration: 0.5, delay: idx * 0.08 }}
                className="group relative overflow-hidden rounded-2xl border border-border-light bg-white p-5 shadow-[0_1px_3px_rgba(0,0,0,0.04)] transition-all duration-300 hover:-translate-y-0.5 hover:border-brand-blue/25 hover:shadow-[0_12px_40px_rgba(27,138,199,0.10)] sm:p-6"
              >
                <div className="flex items-baseline justify-end">
                  <span className="rounded-full border border-border-light bg-surface-secondary px-2.5 py-0.5 font-mono text-[10px] font-semibold uppercase tracking-[0.15em] text-muted">
                    {s.duration}
                  </span>
                </div>
                <h3 className="mt-4 font-display text-xl font-semibold text-heading">
                  {s.title}
                </h3>
                <p className="mt-3 text-sm leading-relaxed text-body">
                  {s.summary}
                </p>
                <div className="mt-4 border-t border-border-light pt-3">
                  <p className="font-mono text-[10px] font-semibold uppercase tracking-[0.2em] text-muted">
                    You get
                  </p>
                  <p className="mt-1 text-xs leading-relaxed text-body/85">
                    {s.deliverable}
                  </p>
                </div>
                {idx < 3 && (
                  <div
                    aria-hidden
                    className="pointer-events-none absolute right-0 top-1/2 hidden -translate-y-1/2 translate-x-1/2 lg:block"
                  >
                    <div className="h-px w-6 bg-gradient-to-r from-brand-blue/40 to-transparent" />
                  </div>
                )}
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ───────── WHY ARTIFLEX IT ───────── */}
      <section className="relative overflow-hidden bg-navy-deep py-16 sm:py-24">
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,rgba(27,138,199,0.18),transparent_60%)]" />
        <div className="shell relative">
          <div className="mx-auto max-w-3xl text-center">
            <p className="font-mono text-xs font-semibold uppercase tracking-[0.25em] text-[#28B5E1]">
              Why Artiflex IT
            </p>
            <h2 className="mt-4 font-display text-3xl font-bold leading-tight text-white sm:text-4xl">
              14+ years of UAE identity delivery
            </h2>
            <p className="mt-5 text-base leading-relaxed text-slate-300 sm:text-lg">
              Vendor-agnostic by design. We will tell you when Microsoft Entra MFA wins, when Okta or Cisco Duo wins, when a FIDO2 key is the only acceptable factor, and when SMS has to go. The point of an honest assessment is honest answers.
            </p>
          </div>

          <div className="mx-auto mt-12 grid max-w-5xl gap-4 sm:mt-16 sm:gap-5 sm:grid-cols-2 lg:grid-cols-4">
            {[
              { value: "80%", label: "Of breaches involve compromised credentials" },
              { value: "$4.9M", label: "Average cost of an identity-related breach" },
              { value: "30s", label: "Time to crack a weak password with modern tools" },
              { value: "99.9%", label: "Of account compromise attacks blocked by MFA" },
            ].map((stat) => (
              <div
                key={stat.label}
                className="rounded-2xl border border-white/10 bg-white/[0.04] p-6 text-center backdrop-blur-sm transition-colors duration-300 hover:border-[#28B5E1]/30"
              >
                <p className="font-display text-3xl font-bold leading-none text-white sm:text-4xl">
                  {stat.value}
                </p>
                <p className="mt-3 text-xs leading-relaxed text-slate-400 sm:text-sm">
                  {stat.label}
                </p>
              </div>
            ))}
          </div>

          <div className="mx-auto mt-12 max-w-4xl rounded-2xl border border-white/10 bg-white/[0.03] p-6 backdrop-blur-sm sm:p-8">
            <div className="grid gap-5 sm:grid-cols-2 sm:gap-6">
              <div>
                <p className="font-mono text-[10px] font-semibold uppercase tracking-[0.2em] text-[#28B5E1]">
                  Vendor coverage
                </p>
                <p className="mt-2 text-sm leading-relaxed text-slate-300">
                  Okta, Microsoft Entra MFA, Cisco Duo, RSA SecurID, Yubico and Google Workspace MFA, active delivery experience across all six.
                </p>
              </div>
              <div>
                <p className="font-mono text-[10px] font-semibold uppercase tracking-[0.2em] text-[#28B5E1]">
                  Compliance frameworks
                </p>
                <p className="mt-2 text-sm leading-relaxed text-slate-300">
                  NESA, UAE PDPL, CBUAE, SAMA, NCA ECC, ISO 27001 and NIST CSF 2.0 aligned implementations, with audit-ready evidence delivered as part of the project.
                </p>
              </div>
              <div>
                <p className="font-mono text-[10px] font-semibold uppercase tracking-[0.2em] text-[#28B5E1]">
                  Coverage area
                </p>
                <p className="mt-2 text-sm leading-relaxed text-slate-300">
                  On-site across Dubai, Abu Dhabi, and Sharjah. Remote across the UAE, Oman, and Saudi Arabia. 24/7 identity operations bench for managed customers.
                </p>
              </div>
              <div>
                <p className="font-mono text-[10px] font-semibold uppercase tracking-[0.2em] text-[#28B5E1]">
                  Engagement model
                </p>
                <p className="mt-2 text-sm leading-relaxed text-slate-300">
                  Fully managed, co-managed, or assessment-only. No vendor lock-in, no theatre, no upselling. The assessment drives the answer.
                </p>
              </div>
            </div>
          </div>

          <div className="mt-10 flex flex-col items-center justify-center gap-3 sm:flex-row sm:gap-4">
            <Link
              to="/contact"
              className="inline-flex items-center justify-center rounded-lg bg-[#28B5E1] px-6 py-3 font-display text-sm font-semibold text-navy-deep transition-colors hover:bg-white sm:text-base"
            >
              Book a free MFA posture assessment
            </Link>
            <Link
              to="/blog/origin-identity-access-management"
              className="inline-flex items-center justify-center rounded-lg border border-white/15 px-6 py-3 font-display text-sm font-medium text-slate-300 transition-colors hover:border-[#28B5E1]/40 hover:text-white sm:text-base"
            >
              Read the full origin story →
            </Link>
          </div>
        </div>
      </section>

      {/* ───────── FAQ ───────── */}
      <section className="relative bg-white py-16 sm:py-24">
        <div className="shell">
          <SectionHeader
            label="Knowledge Base"
            title={
              <>
                Frequently <span className="gradient-text">asked</span> questions
              </>
            }
            description="What UAE decision-makers ask us most about MFA platform selection, phishing-resistant factors, and going passwordless."
            centered
          />

          <div className="mt-12 grid gap-6 sm:mt-14 lg:grid-cols-12 lg:gap-8">
            {/* Questions list (left) */}
            <ul className="flex flex-col gap-2 lg:col-span-6">
              {faqs.map((faq, idx) => {
                const isActive = activeFaq === idx;
                return (
                  <li key={faq.question}>
                    <button
                      type="button"
                      onClick={() => setActiveFaq(idx)}
                      aria-pressed={isActive}
                      aria-controls="faq-answer-panel"
                      className={`group flex w-full items-center justify-between gap-3 rounded-xl border px-4 py-3.5 text-left text-sm font-semibold transition-all duration-200 sm:px-5 sm:text-[15px] ${
                        isActive
                          ? "border-transparent bg-gradient-to-r from-[#045891] to-[#1B8AC7] text-white shadow-[0_8px_24px_-8px_rgba(27,138,199,0.55)]"
                          : "border-slate-200 bg-white text-slate-700 hover:-translate-y-0.5 hover:border-[#28B5E1]/60 hover:bg-slate-50 hover:text-[#1B8AC7]"
                      }`}
                    >
                      <span className="leading-snug">{faq.question}</span>
                      <svg
                        aria-hidden="true"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        strokeWidth="2.2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        className={`h-4 w-4 shrink-0 transition-transform duration-300 ${
                          isActive ? "translate-x-0.5" : "opacity-50 group-hover:translate-x-0.5 group-hover:opacity-100"
                        }`}
                      >
                        <path d="M5 12h14M13 5l7 7-7 7" />
                      </svg>
                    </button>
                  </li>
                );
              })}
            </ul>

            {/* Answer panel (right) */}
            <div className="lg:col-span-6">
              <div
                id="faq-answer-panel"
                role="region"
                aria-live="polite"
                className="lg:sticky lg:top-24"
              >
                <div className="overflow-hidden rounded-2xl border border-transparent bg-gradient-to-r from-[#045891] to-[#054466] p-6 shadow-[0_18px_40px_-18px_rgba(27,138,199,0.55)] sm:p-8">
                  <div className="flex items-center gap-3">
                    <span className="font-mono text-[11px] font-bold uppercase tracking-[0.22em] text-white">
                      Faq
                    </span>
                    <span aria-hidden="true" className="h-px flex-1 bg-gradient-to-r from-white/40 to-transparent" />
                  </div>
                  <h3 className="mt-4 font-display text-xl font-bold leading-snug text-white sm:text-2xl">
                    {faqs[activeFaq].question}
                  </h3>
                  <p className="mt-4 text-sm leading-relaxed text-white/90 sm:text-base">
                    {faqs[activeFaq].answer}
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ───────── CTA ───────── */}
      <CTASection
        title="Get an MFA Readiness Assessment"
        description="60-minute review of your current authentication stack, push-fatigue exposure, and FIDO2 readiness, with a vendor-neutral MFA recommendation mapped to your environment."
        primaryButton={{ text: "Book Assessment", action: "modal" }}
      />
    </>
  );
}
